- README.md
- sql-ballerina/build.gradle
- sql-ballerina/src/sql/Module.md
- sql-ballerina/src/sql/types.bal
- sql-native/build.gradle
- sql-native/src/main/java/org/ballerinalang/sql/Constants.java
- sql-native/src/main/java/org/ballerinalang/sql/utils/CallUtils.java
- sql-native/src/main/java/org/ballerinalang/sql/utils/ErrorGenerator.java
- sql-native/src/main/java/org/ballerinalang/sql/utils/Utils.java
Solve low privilege users not able to run stored procedures
Allow users to define OutParameter types thus enabling all users can run stored procedures.
Fix https://github.com/ballerina-platform/ballerina-lang/issues/25869
As discussed in https://github.com/ballerina-platform/ballerina-lang/issues/25869
Fix low privilege users( Not able to access metadata) run stored procedures
- Unit tests - N/A
- Integration tests Added in MySQL connector
Now `sql:OutParameter` should be changed to specific typed OutParameter class
JDK11, …
> Introduce OutParameter types

- README.md
- sql-ballerina/src/sql/types.bal
$subject instead of union type. 
Reverts temporary fix for https://github.com/ballerina-platform/ballerina-lang/issues/26430
> Define `OutParameter` as object

- sql-native/src/main/java/org/ballerinalang/sql/utils/RecordIteratorUtils.java
- Refactor `RecordIteratorutils` as a part of refactoring `ballerina/sql` to support custom datatype handling for different database connector modules.
- Close issues [#887](https://github.com/ballerina-platform/ballerina-standard-library/issues/887)
- Overload `nextResult()` method. One `nextResult()` includes `ResultParameterHelper` as a parameter. The other gets the sql module's `ResultParameterHelper` singleton instance.
- Change the imports for `convert()` as it has been moved from `Utils` to `ResultParameterHelper` class.
- [SQL Refactor Proposal](https://docs.google.com/document/d/1Xs8pPqEG4aSbGqX1a9C6J-rAjwIe6SmMx0PMkC34xfs/edit?usp=sharing)
- #91 , #92 , #87
> Refactor RecordIteratorutils

- sql-ballerina/types.bal
- To refactor `ballerina/sql` to support custom datatype handling for different database connector modules.
- Issue - [#879](https://github.com/ballerina-platform/ballerina-standard-library/issues/879)
- Added custom object type `CustomTypedValue` to let connectors extend the the parameters to have custom types passed in an SQL query. The parameter value inside this object type is public, hence allows connectors to define parameter classes with the same structure.
- Added `CustomResultIterator` parameter to class `ResultIterator`. It allows passing a custom connector specific ballerina object that contains a custom `nextResult()` function. This custom `nextResult()` will call a connector specific `RecordIteratorUtils.nextResult()`. This enables the connector specific `nextResult()` to …
> Refactor types.bal

- sql-native/src/main/java/org/ballerinalang/sql/parameterprocessor/AbstractResultParameterProcessor.java
- sql-native/src/main/java/org/ballerinalang/sql/parameterprocessor/ResultParameterProcessor.java
- To refactor `ballerina/sql` to support custom datatype handling for different database connector modules.
- Close issues [#880](https://github.com/ballerina-platform/ballerina-standard-library/issues/880) [#883](https://github.com/ballerina-platform/ballerina-standard-library/issues/883)
- The `AbstractResultParameterProcessor` class has the abstract implementation of the methods required to convert the SQL types in the result of database operations into ballerina types and other methods that are related to that task.
- The `ResultParameterProcessor` class contains the implementation of those methods with protected access modifier to allow connector modules to extend the functionality if needed.
- [SQL Refactor Proposal](https://docs.google.com/document/d/1Xs8pPqEG4aSbGqX1a9C6J-rAjwIe6Sm …
> Add Abstract and Concrete ResultParameterProcessor Classes

- sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/QueryProcessor.java
- Add  `QueryProcessor` as a part of refactoring `ballerina/sql` to support custom datatype handling for different database connector modules.
- Close issue [#885](https://github.com/ballerina-platform/ballerina-standard-library/issues/885)
- The logic for executing sql queries is moved from the `utils.QueryUtils` to the new class `nativeimpl.QueryProcessor`.
- The `nativeQuery()` method is overloaded with,
- `nativeQuery()` with `StatementParameterProcessor` and `ResultParameterProcessor` parameters for connector specific parameter processors
- `nativeQuery()` without them which uses the generic parameter  processors in the sql module.
- [SQL Refactor Proposal](https://docs.google.com/document/d/1Xs8pPqEG4aSbGqX1a9C6J-rAjwIe6SmMx0PMkC34xfs/edit?usp=sharing)
- #91 , #92 , #87
> Add Class QueryProcessor to nativeimpl Package

- sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/CallProcessor.java
- sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/ClientProcessor.java
- sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/ExecuteProcessor.java
- sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/OutParameterProcessor.java
- sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/QueryProcessor.java
> Change the license year in the file header of nativeimpl package classes to 2020 from 2021. It is because they are originally created as utils package classes in 2020 and renamed.
> Re Changed Years in nativeimpl

- sql-ballerina/build.gradle
> Renames the extension of the package distribution file from balo to bala 
> Fixes ballerina-platform/ballerina-lang#28476
> Change ballerina archive extension to bala

- sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/OutParameterProcessor.java
- sql-native/src/main/java/org/ballerinalang/sql/parameterprocessor/AbstractResultParameterProcessor.java
- sql-native/src/main/java/org/ballerinalang/sql/parameterprocessor/DefaultResultParameterProcessor.java
- sql-native/src/main/java/org/ballerinalang/sql/utils/RecordIteratorUtils.java
- Rename the convert methods based on the sql type that they are converting to ballerina types in `ConcreteResultParameterProcessor` and `AbstractResultParameterProcessor` and the method invocations.
- Fix the formatting issues due to changed names
> Rename Overloaded "convert" Methods in ResultParameterProcessor

- sql-ballerina/types.bal
- sql-native/src/main/java/org/ballerinalang/sql/datasource/PoolKey.java
- sql-native/src/main/java/org/ballerinalang/sql/datasource/SQLDatasource.java
- sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/CallProcessor.java
- sql-native/src/main/java/org/ballerinalang/sql/parameterprocessor/DefaultStatementParameterProcessor.java
- In the make of `module-ballerinax-oracledb` the additional connection properties should be passed bundled inside a java Properties instance. This is due to oracle data-source exposing a limited no of properties as APIs and letting others to be passed in as a Properties instance. [Documentation](https://docs.oracle.com/cd/E16338_01/appdev.112/e13995/oracle/jdbc/pool/OracleDataSource.html#setConnectionProperties_java_util_Properties_). Therefore it is required to allow a Properties object inside connection initialization options.
- The module contains some bugs that hinder the implementation of connector modules.
- Removed ballerina type checks in the `datasource` package.
- Make Minor Fixes
- Fix issue in call processor comment
- Remove toString() of setVarchar invocation inside …
> Remove Ballerina Type Checks in Connection Init Options

- sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/OutParameterProcessor.java
- sql-native/src/main/java/org/ballerinalang/sql/parameterprocessor/AbstractResultParameterProcessor.java
- sql-native/src/main/java/org/ballerinalang/sql/parameterprocessor/DefaultResultParameterProcessor.java
- sql-native/src/main/java/org/ballerinalang/sql/parameterprocessor/DefaultStatementParameterProcessor.java
Add seperate Methods for Xml and Binary Operations
Move `ConvertBinary` method from `OutParameterProcessor` to `ResultParameterProcessor`.
Create a seperate Method `setXml` in `StatementParameterProcessor` Class.
> Add seperate Methods for Xml and Binary Operations

- sql-ballerina/tests/simple-params-query-test.bal
- sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/QueryProcessor.java
- sql-native/src/main/java/org/ballerinalang/sql/parameterprocessor/DefaultStatementParameterProcessor.java
> $Subject and enable RealValue test case.
Fixes: [#8](https://github.com/ballerina-platform/ballerina-standard-library/issues/8)
> change the set method of preparedStatement from setFloat to setDouble for double value in RealType.
> Fix RealValue datatype precision

- sql-ballerina/tests/complex-query-test.bal
- sql-ballerina/tests/resources/sql/query/complex-test-data.sql
- sql-native/src/main/java/org/ballerinalang/sql/parameterprocessor/DefaultResultParameterProcessor.java
>Update `Convert` functions of Datetime types to give errors if User provides a invalid record in Query Operation
Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/679
> Add Error messages and tests to invalid user records for Datetime Query Operations

- changelog.md
- sql-native/src/main/java/org/ballerinalang/sql/datasource/SQLDatasource.java
- sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/CallProcessor.java
- sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/ExecuteProcessor.java
- sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/QueryProcessor.java
- sql-native/src/main/java/org/ballerinalang/sql/utils/ProcedureCallResultUtils.java
$Title to support db connectors to make their classes isolated.
Fixes:
> Move clientActive flag to java level and remove deprecated usage

- changelog.md
- sql-native/src/main/java/org/ballerinalang/sql/utils/Utils.java
$Title
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1409
> Remove statement.getGeneratedKeys() usage in call execution result

- changelog.md
- sql-ballerina/client.bal
- sql-ballerina/tests/client.bal
- sql-ballerina/tests/complex-query-test.bal
- sql-ballerina/tests/numerical-query-test.bal
- sql-native/src/main/java/org/ballerinalang/sql/Constants.java
- sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/QueryProcessor.java
- sql-native/src/main/java/org/ballerinalang/sql/utils/Utils.java
- sql-test-utils/src/main/java/org/ballerinalang/sql/testutils/QueryTestUtils.java
$title
Earlier, when getting a result set from the `query` remote method of the `jdbc` client, the ballerina developer first has to get the `resultStream` as `stream<record{}, error>` even the return type is provided. Then only developer can cast it to intended `resultStream`. 
Fixes for:
https://github.com/ballerina-platform/ballerina-standard-library/issues/1445
https://github.com/ballerina-platform/ballerina-standard-library/issues/1174
Earlier implementation
```ballerina
type Customer record {|
int customerId;
string lastName;
string firstName;
int registrationId;
float creditLimit;
string country;
|};
jdbc:Client jdbcClient = check new ("jdbc:h2:file:./target/bbes/java_jdbc",
"rootUser", "rootPass");
stream<record{}, error> resultStream =
jdbcClient->query(`SELECT * FROM Customers`, …
```
> Change returning stream type of the query remote method

- ballerina/tests/call-procedures-test.bal
- native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/DefaultResultParameterProcessor.java
In the current implementation of output parameter retrieval of timestamp with timezone, the timezone information was dropped off and only the date & time were returned. This resulted in incorrect UTC values being generated if the stored timezone is different from the local timezone.
This fix first converts the timestamp into the local timezone and returns the correct datetime in UTC. 
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1693
Tested with MySQL, PostgreSQL and MSSQL modules.
> Change UTC return type for output parameters to correspond to local timezone

- native/src/main/java/io/ballerina/stdlib/sql/datasource/SQLWorkerThreadPool.java
Fine-tune the asynchronous thread pool with a maximum number of threads that can be created.
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1764
> Cap the maximum thread that can be created by bal-sql-thread factory

- native/src/main/java/io/ballerina/stdlib/sql/datasource/SQLDatasource.java
- native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/ClientProcessor.java
- native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/ExecuteProcessor.java
- test-utils/src/main/java/io/ballerina/stdlib/sql/testutils/ClientTestUtils.java
On SQL client initialization, two flags need to be passed to define whether Auto Generated Keys should be retrieved when executing queries.
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/1804
Related PR for JDBC: https://github.com/ballerina-platform/module-ballerinax-java.jdbc/pull/245
> Add flags for requesting auto generated keys on query execution

- ballerina/tests/utils.bal
The [previous docker image](https://hub.docker.com/r/blacklabelops/hsqldb) used for HSQLDB only supported `linux/amd64` architectures. The [new docker image](https://hub.docker.com/r/kaneeldias/hsqldb) supports both `linux/amd64` and `linux/arm64` architectures.
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1865
> Change  HSQLDB docker image used in test containers

- ballerina/tests/execute-params-query-test.bal
- changelog.md
- native/src/main/java/io/ballerina/stdlib/sql/Constants.java
- native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/AbstractStatementParameterProcessor.java
- native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/DefaultStatementParameterProcessor.java
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1799
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1800
**Civil Type**
```
time:Utc currentTime = time:utcNow();
time:Civil currentCivil = time:utcToCivil(currentTime);
ParameterizedQuery sqlQuery =
`INSERT INTO DateTimeTypes (row_id, datetime_type) VALUES(${rowId}, ${currentCivil})`;
dbClient->execute(sqlQuery)
```
**UTC Type**
```
time:Utc currentTime = time:utcNow();
ParameterizedQuery sqlQuery =
`INSERT INTO DateTimeTypes (row_id, datetime_type) VALUES(${rowId}, ${currentTime})`;
dbClient->execute(sqlQuery)
```
> Add support for passing ballerina UTC and civil types in parameterized queries

- ballerina/tests/complex-query-test.bal
- ballerina/tests/execute-params-query-test.bal
- changelog.md
- native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/DefaultResultParameterProcessor.java
- native/src/main/java/io/ballerina/stdlib/sql/utils/Utils.java
$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1909
```
time:Utc retrievedTimeUtc = check dbClient->queryRow(`
SELECT timestamp_tz_type from DateTimeTypes where row_id = 1
`);
```
> Add support for retrieving time:Utc type

- ballerina/client.bal
- ballerina/tests/batch-execute-query-test.bal
- ballerina/tests/client.bal
- ballerina/tests/query-row-test.bal
- ballerina/tests/utils.bal
- changelog.md
- native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/ExecuteProcessor.java
- native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/QueryProcessor.java
- test-utils/src/main/java/io/ballerina/stdlib/sql/testutils/QueryTestUtils.java
$subject part of https://github.com/ballerina-platform/ballerina-standard-library/issues/1880
> Remove string usages from batchexecute and queryRow api

- ballerina/tests/query-row-test.bal
- changelog.md
- native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/QueryProcessor.java
$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2333
`record {}|int count = check dbClient->queryRow(sqlQuery);`
> Add support for union types in queryRow API

- ballerina/client.bal
- ballerina/tests/client.bal
- changelog.md
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2390
https://github.com/ballerina-platform/module-ballerinax-mssql/pull/93
https://github.com/ballerina-platform/module-ballerinax-java.jdbc/pull/291
https://github.com/ballerina-platform/module-ballerinax-oracledb/pull/72
https://github.com/ballerina-platform/module-ballerinax-mysql/pull/291
https://github.com/ballerina-platform/module-ballerinax-mssql/pull/93
> Change queryRow() API accept anydata as the return-type instead of any

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/tests/call-procedures-test.bal
- ballerina/types.bal
- changelog.md
- native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/OutParameterProcessor.java
- native/src/test/java/io/ballerina/stdlib/sql/nativeimpl/OutParameterProcessorTest.java
$subject
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/2388
> Make OutParameter get function parameter optional

- changelog.md
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/sql/compiler/CompilerPluginTest.java
- compiler-plugin-tests/src/test/resources/diagnostics/sample4/Ballerina.toml
- compiler-plugin-tests/src/test/resources/diagnostics/sample4/main.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/analyzer/ConnectionPoolConfigAnalyzer.java
$subject
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/2536
N/A
> Fix plugin crash when variable is passed for `ConnectionPool`

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/tests/complex-query-test.bal
- ballerina/tests/query-row-test.bal
- changelog.md
- native/src/main/java/io/ballerina/stdlib/sql/Constants.java
- native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/QueryProcessor.java
- native/src/main/java/io/ballerina/stdlib/sql/utils/RecordIteratorUtils.java
- native/src/main/java/io/ballerina/stdlib/sql/utils/Utils.java
$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2985
> Fix NullPointerException when retrieving record with default value

- ballerina/tests/simple-params-query-test.bal
- ballerina/utils.bal
- changelog.md
$subject 
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3127
N/A
> Fix sql:queryConcat not working for empty query

- .trivyignore
$subject since the fixed version 2.7.1 is not released yet and no released date announced (https://hsqldb.org)
Since this dependency is used only for testing purposes this is a false positive.
Fixes:
> Defer vulnerability till october end

- ballerina/connection-pool.bal
- ballerina/tests/connection-init-test.bal
- changelog.md
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/sql/compiler/CompilerPluginTest.java
- compiler-plugin-tests/src/test/resources/diagnostics/sample1/main.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/SQLDiagnosticsCodes.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/analyzer/ConnectionPoolConfigAnalyzer.java
- native/src/main/java/io/ballerina/stdlib/sql/datasource/SQLDatasource.java
$subject
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/3657
> Fix Unable to set unlimited life time (0) to ballerina.sql.maxConnectionLifeTime

- ballerina/metadata_types.bal
- ballerina/tests/metadata-test.bal
- ballerina/tests/schema_client.bal
Will move the CheckContraints record from being a field of ColumnDefinition to being a field of TableDefinition.
Mentor: @daneshk
> Moving CheckConstraints to table level

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- changelog.md
- compiler-plugin-tests/build.gradle
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/sql/compiler/CompilerPluginTest.java
- compiler-plugin-tests/src/test/resources/diagnostics/sample5/Ballerina.toml
- compiler-plugin-tests/src/test/resources/diagnostics/sample5/main.bal
- compiler-plugin-tests/src/test/resources/diagnostics/sample5/tests/tests.bal
- compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/analyzer/MethodAnalyzer.java
- gradle.properties
$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4054
> Fix SQL compiler plugins failure when the diagnostic code is null

- ballerina/annotation.bal
- changelog.md
- docs/spec/spec.md
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4134
> Indicate sql:Column annotation can only be used with Typed records

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- gradle.properties
> Update http and module versions

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/tests/execute-params-query-test.bal
- codecov.yml
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/sql/compiler/CompilerPluginTest.java
- compiler-plugin-tests/src/test/resources/diagnostics/sample3/Ballerina.toml
- compiler-plugin-tests/src/test/resources/diagnostics/sample3/main.bal
Related to https://github.com/ballerina-platform/ballerina-library/issues/5872
Local build with latest language commit passes. This needs to be investigated further. Temporarily disabling the testcases as many are blocked on this.
> Temporarily disable testInvalidConnectionParamConfig test

- codecov.yml
- compiler-plugin-tests/src/test/resources/testng.xml
This reverts commit 9645c801bb44695f9ad43f0b73aa8f9eb36e4b1f.
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/5872
Enabling the testcases as the original issue is fixed
> Revert "Disable all compiler plugin tests"

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- gradle.properties
- native/src/main/java/io/ballerina/stdlib/sql/utils/ProcedureCallResultUtils.java
- native/src/main/java/io/ballerina/stdlib/sql/utils/RecordIteratorUtils.java
- native/src/test/java/io/ballerina/stdlib/sql/nativeimpl/OutParameterProcessorTest.java
$subject. due to new API introduction
> Update the sql version to the next minor

- native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/CallProcessor.java
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/6626
> Properly close resources for call procedure failure

- native/src/main/java/io/ballerina/stdlib/sql/datasource/SQLDatasource.java
- native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/CallProcessor.java
- native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/ExecuteProcessor.java
- native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/QueryProcessor.java
> Improve performance of SQL database calls inside transaction contexts

- .github/workflows/build-timestamped-master.yml
- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- gradle.properties
- native/src/main/java/io/ballerina/stdlib/sql/Constants.java
- native/src/main/java/io/ballerina/stdlib/sql/datasource/SQLWorkerThreadPool.java
> Make maximum sql pool size configurable

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/tests/query-row-test.bal
- changelog.md
- native/src/main/java/io/ballerina/stdlib/sql/datasource/SQLWorkerThreadPool.java
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/7244
The **SynchronousQueue** does not buffer tasks and only acts as a hand-off point. This causes the **ThreadPoolExecutor** to fail with a **RejectedExecutionException**, leading to unexecuted tasks and causing the Ballerina future to remain incomplete. As a result, the Ballerina strand hangs indefinitely.
Changing the **SynchronousQueue** to a **LinkedBlockingQueue** allows for task buffering, which eliminates the **RejectedExecutionException** and improves task execution.
> Fix strand hanging when strand count exceeds BALLERINA_SQL_MAX_POOL_SIZE

- ballerina/tests/query-row-test.bal
- changelog.md
- native/src/main/java/io/ballerina/stdlib/sql/datasource/SQLWorkerThreadPool.java
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/7244
> [2201.9.x] Fix strand hanging when strand count exceeds BALLERINA_SQL_MAX_POOL_SIZE

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- gradle.properties
Related to: https://github.com/ballerina-platform/module-ballerina-sql/pull/739
> [2201.8.x] Update sql version to 1.12.3

- ballerina/Dependencies.toml
- native/src/main/java/io/ballerina/stdlib/sql/datasource/SQLWorkerThreadPool.java
Fixes: https://github.com/ballerina-platform/ballerina-library/issues/7308
> [2201.9.x] Improve query performance

- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/build.gradle
- build.gradle
- compiler-plugin-tests/build.gradle
- compiler-plugin/build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- native/build.gradle
- settings.gradle
- test-utils/build.gradle
> Bump the Dependencies for Update 11 Release

- gradle.properties
- native/src/test/java/io/ballerina/stdlib/sql/TestUtils.java
An interface `IterableValue` will be introduced for the ballerina collections that supported query, which will enable to get a Java `Iterator` from ballerina collections. `BArray` and `BMap` will extend these interface. As following two return instances from `BArray `and `BMap`, they should implement the method `getJavaIterator()` .
https://github.com/ballerina-platform/module-ballerina-sql/blob/f90668f0196d54c6efef58a5ecce81710591cc38/native/src/test/java/io/ballerina/stdlib/sql/TestUtils.java#L1142 
and 
https://github.com/ballerina-platform/module-ballerina-sql/blob/f90668f0196d54c6efef58a5ecce81710591cc38/native/src/test/java/io/ballerina/stdlib/sql/TestUtils.java#L907
Note: **This PR should be merged after the `query changes` in `Ballerina Lang 2201.13.0` are released**.
Fixes:
> Implement getJavaIterator() for BArray and BMap (Merge After Lang 2201.13.0 Query Changes)
