ballerina-platform/module-ballerina-sql

README.md
sql-ballerina/src/sql/tests/execute/execute-basic-test.bal
sql-ballerina/src/sql/tests/execute/execute-params-query-test.bal
sql-ballerina/src/sql/tests/query/complex-query-test.bal
sql-ballerina/src/sql/tests/query/numerical-query-test.bal
sql-ballerina/src/sql/tests/query/simple-params-query-test.bal
sql-ballerina/src/sql/tests/transaction/local-transaction-test.bal
sql-ballerina/src/sql/tests/utils.bal

Enable date time testcases

---

README.md

Tweak README labels

---

README.md

Review the SQL Module README File.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, …

Review the SQL Module README File

---

build.gradle

**Depends on https://github.com/ballerina-platform/module-ballerina-runtime/pull/4**

Fix runtime std lib depedancy

---

README.md
sql-ballerina/src/sql/tests/mockclient/client.bal
sql-ballerina/src/sql/types.bal

Migrating change as per ballerina-lang update in https://github.com/ballerina-platform/ballerina-lang/pull/25228

Remove public keyword in function params

---

README.md
sql-ballerina/build.gradle
sql-ballerina/src/sql/tests/query/simple-params-query-test.bal
sql-ballerina/src/sql/tests/transaction/local-transaction-test.bal

Streamline & Fix build 

---

sql-ballerina/src/sql/client.bal
sql-ballerina/src/sql/connection-pool.bal
sql-ballerina/src/sql/tests/mockclient/client.bal
sql-ballerina/src/sql/types.bal

Add Ballerina class support

---

sql-native/src/main/java/org/ballerinalang/sql/Constants.java
sql-native/src/main/java/org/ballerinalang/sql/datasource/PoolKey.java
sql-native/src/main/java/org/ballerinalang/sql/datasource/SQLDatasource.java
sql-native/src/main/java/org/ballerinalang/sql/datasource/SQLDatasourceUtils.java
sql-native/src/main/java/org/ballerinalang/sql/transaction/SQLTransactionContext.java
sql-native/src/main/java/org/ballerinalang/sql/utils/CallUtils.java
sql-native/src/main/java/org/ballerinalang/sql/utils/ClientUtils.java
sql-native/src/main/java/org/ballerinalang/sql/utils/ConnectionPoolUtils.java
sql-native/src/main/java/org/ballerinalang/sql/utils/ErrorGenerator.java
sql-native/src/main/java/org/ballerinalang/sql/utils/ExecuteUtils.java
sql-native/src/main/java/org/ballerinalang/sql/utils/OutParameterUtils.java
sql-native/src/main/java/org/ballerinalang/sql/utils/ProcedureCallResultUtils.java
sql-native/src/main/java/org/ballerinalang/sql/utils/QueryUtils.java
sql-native/src/main/java/org/ballerinalang/sql/utils/RecordIteratorUtils.java
sql-native/src/main/java/org/ballerinalang/sql/utils/Utils.java

Migrate jBallerina Runtime APIs

---

.github/workflows/pull-request.yml
sql-native/src/main/java/org/ballerinalang/sql/utils/RecordIteratorUtils.java

$subject
Enable secrets to PR build from forks

Fix sql-native build

---

sql-ballerina/src/sql/client.bal
sql-ballerina/src/sql/connection-pool.bal
sql-ballerina/src/sql/types.bal

Add isolate keyword change

---

sql-ballerina/src/sql/client.bal

Make generateApplicationErrorStream as isolated

---

sql-ballerina/build.gradle

Fix test command dependency

---

build.gradle

Streamline configs

---

build.gradle

Reverts ballerina-platform/module-ballerina-sql#23
This adds buildTask configs to release plugin

Revert "Streamline configs"

---

.gitignore

Update gitignore file with ballerina.lock

---

README.md

Add openjdk link

---

sql-native/src/main/java/module-info.java
sql-native/src/main/java/org/ballerinalang/sql/Constants.java
sql-native/src/main/java/org/ballerinalang/sql/datasource/PoolKey.java
sql-native/src/main/java/org/ballerinalang/sql/datasource/SQLDatasource.java
sql-native/src/main/java/org/ballerinalang/sql/datasource/SQLDatasourceUtils.java
sql-native/src/main/java/org/ballerinalang/sql/transaction/SQLTransactionContext.java
sql-native/src/main/java/org/ballerinalang/sql/utils/CallUtils.java
sql-native/src/main/java/org/ballerinalang/sql/utils/ClientUtils.java
sql-native/src/main/java/org/ballerinalang/sql/utils/ColumnDefinition.java
sql-native/src/main/java/org/ballerinalang/sql/utils/ConnectionPoolUtils.java
sql-native/src/main/java/org/ballerinalang/sql/utils/ErrorGenerator.java
sql-native/src/main/java/org/ballerinalang/sql/utils/ExecuteUtils.java
sql-native/src/main/java/org/ballerinalang/sql/utils/OutParameterUtils.java
sql-native/src/main/java/org/ballerinalang/sql/utils/ProcedureCallResultUtils.java
sql-native/src/main/java/org/ballerinalang/sql/utils/QueryUtils.java
sql-native/src/main/java/org/ballerinalang/sql/utils/RecordIteratorUtils.java
sql-native/src/main/java/org/ballerinalang/sql/utils/Utils.java

Refactor ballerina runtime api usages
Dependant https://github.com/ballerina-platform/ballerina-lang/pull/26278

Migrate ballerina runtime apis

---

README.md
sql-ballerina/src/sql/connection-pool.bal

$subject as this is accessed from isolated functions

Mark GlobalConnectionPoolContainer as readonly

---

README.md

Update README with updated issues link

---

sql-native/src/main/java/org/ballerinalang/sql/utils/CallUtils.java

$subject to fix NPE thrown when InOutParameter is processed

Add inoutparameter to populate list

---

sql-ballerina/src/sql/error.bal

$subject migrating as per https://github.com/ballerina-platform/ballerina-lang/pull/26629

Change error detail to open record

---

sql-ballerina/src/sql/Module.md

> Information related to SP calls have been updated in Module.md

Update Module.md with info related to SP calls

---

sql-ballerina/src/sql/tests/transaction/local-transaction-test.bal

These reverts commit e7001356 as the original issue is fixed by https://github.com/ballerina-platform/ballerina-lang/pull/26999

Revert "Disable transaction testcases temporarily"

---

sql-ballerina/build.gradle

Enable doc creation

---

sql-ballerina/tests/local-transaction-test.bal

Enable transaction testcase

---

gradle.properties

Bump transactions internal module version

---

sql-ballerina/Package.md
sql-ballerina/tests/local-transaction-test.bal

$subject as issue https://github.com/ballerina-platform/ballerina-lang/issues/27381 is fixed

Reenable test assertions for transactions

---

.github/workflows/build-master.yml
.github/workflows/pull-request.yml
sql-ballerina/tests/local-transaction-test.bal

$subject design discussion raised in https://github.com/ballerina-platform/ballerina-standard-library/issues/727

Temporarily fix transaction retry test cases

---

build.gradle
gradle.properties
sql-ballerina/tests/batch-execute-query-test.bal
sql-ballerina/tests/execute-basic-test.bal
sql-ballerina/tests/execute-params-query-test.bal
sql-ballerina/tests/local-transaction-test.bal

Migrate testerina API change

---

build.gradle
gradle.properties
sql-ballerina/tests/complex-query-test.bal
sql-ballerina/tests/connection-pool-test.bal

Migrate to regex module

---

sql-ballerina/tests/local-transaction-test.bal

> Sync test with marking commit/rollback handlers as isolated
> Link to the PR for changes to the training content in …

Sync with transaction handlers set as isolated

---

sql-ballerina/build.gradle

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Update ballerina command to bal command

---

sql-native/src/main/java/org/ballerinalang/sql/datasource/SQLDatasourceUtils.java

> Describe the problems, issues, or needs driving this feature/fix and include links to related issues in the following format: Resolves issue1, issue2, etc.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Disable autocomiting when atomikos is used as XA transaction manager manager

---

sql-native/src/main/java/org/ballerinalang/sql/utils/Utils.java

Update module with time module changes

---

sql-ballerina/Config.toml
sql-ballerina/connection-pool.bal

$subject
Some config API parts are not migrated due to module-ballerina-auth dependency. 
N/A
N/A
N/A
N/A
[BBE](https://ballerina.io/swan-lake/learn/by-example/configurable.html)
N/A
N/A
N/A
- Unit tests 
>  N/A
- Integration tests
> N/A
N/A
> Describe migration steps and platforms on which migration has been tested
jdk-11.0 , Linux

Migrate to configurable variables

---

build.gradle
gradle.properties
sql-ballerina/Ballerina.toml
sql-ballerina/build.gradle

Remove config module dependency

---

sql-ballerina/client.bal
sql-ballerina/connection-pool.bal
sql-ballerina/init.bal
sql-ballerina/tests/client.bal
sql-ballerina/types.bal

Related Issue: ballerina-platform/ballerina-lang#28034
> Link to the PR for changes to the training content in …

Change the name of the `java` langlib module to `jballerina.java`

---

sql-ballerina/Ballerina.toml
sql-ballerina/Dependencies.toml
sql-ballerina/build.gradle

Fixes ballerina-platform/ballerina-lang#27988

Add Dependencies.toml

---

sql-ballerina/tests/client.bal

> Refactor SQL Module
Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/879
> Refactor the Ballerina test client to access processor classes.
> Change the Class name to the relevant Java Class name.
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this …

Refactor the test client

---

sql-native/src/main/java/org/ballerinalang/sql/parameterprocessor/AbstractStatementParameterProcessor.java
sql-native/src/main/java/org/ballerinalang/sql/parameterprocessor/StatementParameterProcessor.java

> Refactor SQL Module
Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/881, https://github.com/ballerina-platform/ballerina-standard-library/issues/886
> Introduce StatementParameterProcessor class and AbstractStatementParameterProcessor class to implement methods required convert ballerina types into SQL types and
other methods that process the parameters of the statement.
>Implement the connector specific usecases as abstract and allow connector modules to implement the connector specific logic.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief …

Add StatementParameterProcessor Class and AbstractStatementParameterProcessor Class.

---

sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/CallProcessor.java

> Refactor SQL Module
Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/889.
> Implement the CallProcessor class with call method.
> Allow connector modules to handle connector specific logic by passing the connector specific StatementParameterProcessor and ResultParameterProcessor objects.
> Type “Sent” when you have provided new/updated certification …

Add CallProcessor

---

sql-native/src/main/java/org/ballerinalang/sql/utils/ProcedureCallResultUtils.java

> Refactor SQL module
> Refactor ProcedureCallResultUtils class

Refactor procedurecallresult

---

sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/ClientProcessor.java
sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/OutParameterProcessor.java

> Refactor SQL Module
> Add nativeimpl package

Add ClientProcessor and OutParameterProcessor class

---

build-config/spotbugs-exclude.xml

> Refactor the SQL Module
Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/879
> Refactor the  spotbug-exclude.xml file.
> Change the class names and add the OBL_UNSATISFIED_OBLIGATION filter.
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this …

Refactor the  spotbug-exclude.xml file

---

README.md
sql-ballerina/Package.md

> This is to change the URLs consists of /swan-lake

Change the URL links consists of /swan-lake

---

.github/workflows/publish-release.yml
README.md
gradle.properties
sql-ballerina/Package.md
sql-ballerina/build.gradle

> This is to change the string module -> package in .md files.

Change string module -> package in .md files

---

build.gradle
sql-ballerina/build.gradle

Re-order build tasks to publish to ballerina central

---

sql-ballerina/build.gradle

Fix ballerina push not working

---

sql-ballerina/tests/complex-query-test.bal
sql-ballerina/tests/connection-pool-test.bal

Fix for removal of error type from anydata

---

sql-ballerina/tests/local-transaction-test.bal

Disable intermittently failing test case

---

sql-ballerina/types.bal
sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/CallProcessor.java
sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/ClientProcessor.java
sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/ExecuteProcessor.java
sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/QueryProcessor.java

- Add Java Doc comments for NativeImpl API methods exposed
- Fix the name of `ResultParameterProcessor` and `StatmentParameterprocessor` instances in `QueryProcessor` class.
- Sync with master
- Fix reverted changes

API Documentation for NativeImpl Package

---

sql-native/src/main/java/org/ballerinalang/sql/datasource/SQLDatasource.java
sql-native/src/main/java/org/ballerinalang/sql/parameterprocessor/DefaultResultParameterProcessor.java

> Refactor Datasource and ResultParameterProcessor classes.

Refactor Datasource and ResultParameterProcessor

---

sql-ballerina/Config.toml
sql-ballerina/connection-pool.bal
sql-ballerina/tests/connection-init-test.bal
sql-native/src/main/java/org/ballerinalang/sql/Constants.java
sql-native/src/main/java/org/ballerinalang/sql/datasource/SQLDatasource.java

> $Subject
> fixes [#967](https://github.com/ballerina-platform/ballerina-standard-library/issues/967)
@shafreenAnfar 
> …

Change durations such as timeouts, intervals, etc

---

sql-ballerina/build.gradle

> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763

Add extracted bala in the zip artifact

---

sql-ballerina/build.gradle

Filter only package native classes and ballerina classes for test coverage report using includes flag.
Fixes ballerina-platform/ballerina-lang#28951
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …

Add specific includes for code coverage

---

sql-ballerina/build.gradle

> Add -c flag to build command
> Related to ballerina-platform/ballerina-lang#29032

Add -c flag to build command

---

gradle.properties
sql-ballerina/tests/complex-query-test.bal
sql-ballerina/tests/simple-params-query-test.bal
sql-ballerina/types.bal
sql-native/src/main/java/org/ballerinalang/sql/parameterprocessor/DefaultStatementParameterProcessor.java
sql-native/src/main/java/org/ballerinalang/sql/utils/Utils.java

> This PR is to change the old Time module APIs with New APIs and change the test cases as well.
Fixes: [#1079](https://github.com/ballerina-platform/ballerina-standard-library/issues/1079)
> @daneshk @niveathika @BuddhiWathsala 
> https://github.com/ballerina-platform/module-ballerina-time/pull/68
> https://github.com/ballerina-platform/ballerina-standard-library/issues/1079

New Time APIs migration and change test cases

---

sql-ballerina/client.bal
sql-ballerina/tests/client.bal
sql-ballerina/tests/connection-pool-test.bal
sql-ballerina/tests/local-transaction-test.bal
sql-ballerina/tests/utils.bal

> $Subject 
> provide isolated APIs to db client module users.

Change module APIs to isolated

---

sql-ballerina/types.bal
sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/OutParameterProcessor.java
sql-native/src/main/java/org/ballerinalang/sql/parameterprocessor/AbstractResultParameterProcessor.java
sql-native/src/main/java/org/ballerinalang/sql/parameterprocessor/DefaultResultParameterProcessor.java
sql-native/src/main/java/org/ballerinalang/sql/utils/ColumnDefinition.java
sql-native/src/main/java/org/ballerinalang/sql/utils/Utils.java

> Change access modifiers and method parameters to make extendable for connector modules

Change access modifiers and method parameters to make extendable for connector modules 

---

sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/CallProcessor.java
sql-native/src/main/java/org/ballerinalang/sql/parameterprocessor/DefaultResultParameterProcessor.java
sql-native/src/main/java/org/ballerinalang/sql/utils/RecordIteratorUtils.java
sql-native/src/main/java/org/ballerinalang/sql/utils/Utils.java

> $Subject
> Remove unnecessary calendar objects from the code base.
> https://github.com/ballerina-platform/module-ballerina-sql/pull/161

Remove calendar objects from several classes

---

.github/workflows/build-master.yml
.github/workflows/publish-release.yml
sql-ballerina/build.gradle
sql-native/build.gradle

$subject
part of https://github.com/ballerina-platform/ballerina-standard-library/issues/1198

Use separate config for Github package publish

---

sql-ballerina/types.bal
sql-native/src/main/java/org/ballerinalang/sql/parameterprocessor/DefaultResultParameterProcessor.java

Change Out parameter classes to distinct type and fix a bug when returning time and timestamp type
#161

More distinct data types and bug fix

---

sql-ballerina/tests/batch-execute-query-test.bal
sql-ballerina/tests/call-procedures-test.bal
sql-ballerina/tests/complex-query-test.bal
sql-ballerina/tests/connection-init-test.bal
sql-ballerina/tests/connection-pool-test.bal
sql-ballerina/tests/execute-basic-test.bal
sql-ballerina/tests/execute-params-query-test.bal
sql-ballerina/tests/local-transaction-test.bal
sql-ballerina/tests/numerical-query-test.bal
sql-ballerina/tests/simple-params-query-test.bal
sql-ballerina/tests/utils.bal

>Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/1243

Changed checkpanic keyword to check and changed capitalized variables to lowercase in test functions

---

sql-native/src/main/java/org/ballerinalang/sql/datasource/SQLDatasource.java

$Subject
Related issues: 
[#1131](https://github.com/ballerina-platform/ballerina-standard-library/issues/1131)
[#178](https://github.com/ballerina-platform/ballerina-standard-library/issues/178)
[#177](https://github.com/ballerina-platform/ballerina-standard-library/issues/177)

Improve the error message for ClassNotFoundException

---

build.gradle
sql-ballerina/build.gradle

Strip stdlib dependency version

---

sql-ballerina/build.gradle

Improve test coverage filter

---

codecov.yml

Add configuration for codecov badge colour

---

sql-ballerina/tests/execute-params-query-test.bal
sql-ballerina/tests/resources/sql/query/simple-params-test-data.sql
sql-ballerina/tests/simple-params-query-test.bal
sql-native/src/main/java/org/ballerinalang/sql/Constants.java
sql-native/src/main/java/org/ballerinalang/sql/parameterprocessor/DefaultResultParameterProcessor.java
sql-native/src/main/java/org/ballerinalang/sql/parameterprocessor/DefaultStatementParameterProcessor.java

$SUbject
Related issue: [#1343](https://github.com/ballerina-platform/ballerina-standard-library/issues/1343)

Enable the query param in the test case

---

changelog.md

Add the content in the changelog file

---

sql-ballerina/build.gradle

Set flag to enable Jacoco Coverage XML generation. Fixes https://github.com/ballerina-platform/ballerina-lang/issues/30381

Set flag to enable Jacoco Coverage XML generation

---

sql-ballerina/build.gradle

Update flag for coverage format from '--jacoco-xml' to '--coverage-format=xml'

Update flag for coverage format

---

sql-ballerina/Module.md
sql-ballerina/tests/client.bal
sql-ballerina/tests/connection-init-test.bal
sql-ballerina/tests/connection-pool-test.bal
sql-native/src/main/java/org/ballerinalang/sql/Constants.java
sql-native/src/main/java/org/ballerinalang/sql/datasource/SQLDatasource.java
sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/CallProcessor.java
sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/ClientProcessor.java
sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/ExecuteProcessor.java
sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/QueryProcessor.java

$Title
Fixes: The issue had in java.jdbc and mysql build failure.

Remove using poolShutdown flag as the clientActive status

---

.github/workflows/build-timestamped-master.yml
.github/workflows/publish-release.yml

Update ballerina plugin version to 0.9.0

---

sql-ballerina/Package.md

$Subject
Related issue: ballerina-platform/ballerina-standard-library#1462

Update Package.md links into HTML format

---

sql-ballerina/Module.md

$tiitle
Fix for: https://github.com/ballerina-platform/ballerina-standard-library/issues/1463

Update API docs

---

sql-native/src/main/java/org/ballerinalang/sql/parameterprocessor/DefaultResultParameterProcessor.java
sql-native/src/main/java/org/ballerinalang/sql/parameterprocessor/DefaultStatementParameterProcessor.java
sql-native/src/main/java/org/ballerinalang/sql/utils/ProcedureCallResultUtils.java
sql-native/src/main/java/org/ballerinalang/sql/utils/RecordIteratorUtils.java

Remove private constructors to fix the issue in other db connectors

---

sql-ballerina/tests/connection-init-test.bal

Improve Code Coverage

---

sql-native/src/main/java/org/ballerinalang/sql/nativeimpl/ExecuteProcessor.java

Fixes:
https://github.com/ballerina-platform/ballerina-standard-library/issues/1568

Add support to handle batch execute with generated keys optional

---

.github/workflows/publish-release.yml

Improve post release tasks in workflows

---

sql-ballerina/Module.md
sql-ballerina/types.bal

$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1538
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/1537

Fix documentation

---

.github/workflows/pull-request.yml
build-config/checkstyle/build.gradle
sql-ballerina/Ballerina.toml
sql-native/build.gradle

Remove redundant configurations

---

sql-ballerina/tests/complex-query-test.bal
sql-ballerina/tests/execute-params-query-test.bal
sql-ballerina/tests/resources/sql/query/complex-test-data.sql
sql-ballerina/tests/simple-params-query-test.bal
sql-native/src/main/java/org/ballerinalang/sql/datasource/PoolKey.java
sql-native/src/main/java/org/ballerinalang/sql/utils/ColumnDefinition.java
sql-native/src/test/java/org/ballerinalang/sql/tests/TestUtils.java
sql-native/src/test/java/org/ballerinalang/sql/tests/datasource/PoolKeyTest.java
sql-native/src/test/java/org/ballerinalang/sql/tests/nativeimpl/OutParameterProcessorTest.java
sql-native/src/test/java/org/ballerinalang/sql/tests/parameterprocessor/DefaultResultParameterProcessorTest.java
sql-native/src/test/java/org/ballerinalang/sql/tests/parameterprocessor/DefaultStatementParameterProcessorTest.java
sql-native/src/test/java/org/ballerinalang/sql/tests/transaction/SQLTransactionContextTest.java
sql-native/src/test/java/org/ballerinalang/sql/tests/utils/ColumnDefinitionTest.java
sql-native/src/test/java/org/ballerinalang/sql/tests/utils/UtilsTest.java

Fix for : https://github.com/ballerina-platform/ballerina-standard-library/issues/1455

Improve test coverage

---

native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/CallProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/ExecuteProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/OutParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/QueryProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/AbstractResultParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/AbstractStatementParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/DefaultResultParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/DefaultStatementParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/utils/RecordIteratorUtils.java
native/src/test/java/io/ballerina/stdlib/sql/tests/parameterprocessor/DefaultResultParameterProcessorTest.java
native/src/test/java/io/ballerina/stdlib/sql/tests/parameterprocessor/DefaultStatementParameterProcessorTest.java

$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1590

Improve abstraction of SQL native code

---

native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/OutParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/AbstractResultParameterProcessor.java

Make OutParameterProcessor use abstract methods

---

native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/AbstractResultParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/AbstractStatementParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/DefaultResultParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/DefaultStatementParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/utils/RecordIteratorUtils.java
native/src/test/java/io/ballerina/stdlib/sql/tests/parameterprocessor/DefaultResultParameterProcessorTest.java

$title
This change allows other db modules to override the setting and converting xml methods according to their db driver implementations. 
Fixes:

Update getResult method in RecordIteratorUtils class

---

ballerina/tests/numerical-query-test.bal
changelog.md
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/QueryProcessor.java

$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1759

Fix type cast error for query api containing database error

---

ballerina/client.bal
ballerina/tests/batch-execute-query-test.bal
ballerina/tests/client.bal
build-config/spotbugs-exclude.xml
changelog.md
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/ExecuteProcessor.java

$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1529

Improve batch execute method to include string array

---

ballerina/error.bal
ballerina/tests/query-row-test.bal
changelog.md
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/ClientProcessor.java

$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/1805

[Phase 1] Introduce improved Error Hierarchy

---

ballerina/tests/simple-params-query-test.bal
ballerina/types.bal
native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/AbstractStatementParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/DefaultStatementParameterProcessor.java

Add passing record types directly to parameterizedQuery support

---

native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/DefaultResultParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/DefaultStatementParameterProcessor.java
native/src/test/java/io/ballerina/stdlib/sql/tests/parameterprocessor/DefaultResultParameterProcessorTest.java
native/src/test/java/io/ballerina/stdlib/sql/tests/parameterprocessor/DefaultStatementParameterProcessorTest.java

Introduce SQLException for custom data processing api

---

README.md
ballerina/tests/call-procedures-test.bal
changelog.md
native/src/main/java/io/ballerina/stdlib/sql/exception/TypeMismatchError.java
native/src/main/java/io/ballerina/stdlib/sql/utils/Utils.java
native/src/test/java/io/ballerina/stdlib/sql/tests/exception/ApplicationErrorTest.java

$subject
Fixes: [1875](https://github.com/ballerina-platform/ballerina-standard-library/issues/1875)

Fix Error message for array type conversion

---

ballerina/tests/call-procedures-test.bal
ballerina/tests/complex-query-test.bal
ballerina/tests/connection-init-test.bal
ballerina/tests/connection-pool-test.bal
ballerina/tests/execute-basic-test.bal
ballerina/tests/execute-params-query-test.bal
ballerina/tests/local-transaction-test.bal
ballerina/tests/numerical-query-test.bal
ballerina/tests/simple-params-query-test.bal

$subject as part of https://github.com/ballerina-platform/ballerina-standard-library/issues/1880

Remove usage of strings for queries in test cases

---

ballerina/Module.md

$subject for proper formatting in API docs

Adjust line length of code snippets

---

ballerina/Module.md

Add package prefix in documentation

---

ballerina/client.bal
ballerina/tests/call-procedures-test.bal
ballerina/tests/client.bal
ballerina/tests/execute-basic-test.bal
ballerina/tests/numerical-query-test.bal
ballerina/tests/utils.bal
changelog.md
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/CallProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/ExecuteProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/QueryProcessor.java
test-utils/src/main/java/io/ballerina/stdlib/sql/testutils/CallTestUtils.java
test-utils/src/main/java/io/ballerina/stdlib/sql/testutils/ExecuteTestUtils.java
test-utils/src/main/java/io/ballerina/stdlib/sql/testutils/QueryTestUtils.java

$subject
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/2010

Depreciate string param in APIs

---

ballerina/Ballerina.toml
build-config/resources/Ballerina.toml

Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2051
N/A

Improve Ballerina toml with package properties

---

ballerina/Dependencies.toml
ballerina/tests/array-params-query-test.bal
ballerina/tests/call-procedures-test.bal
ballerina/tests/complex-query-test.bal
ballerina/tests/connection-init-test.bal
ballerina/tests/connection-pool-test.bal
ballerina/tests/execute-basic-test.bal
ballerina/tests/execute-params-query-test.bal
ballerina/tests/local-transaction-test.bal
ballerina/tests/numerical-query-test.bal
ballerina/tests/query-row-test.bal
ballerina/tests/record-mapping-test.bal
ballerina/tests/utils.bal

Remove unused variables in tests

---

ballerina/types.bal
native/src/main/java/io/ballerina/stdlib/sql/utils/RecordIteratorUtils.java

Refactor cleanup resources logic to native code in case of error/completion

---

.github/workflows/build-timestamped-master.yml
ballerina/tests/connection-init-test.bal
changelog.md
native/src/main/java/io/ballerina/stdlib/sql/datasource/SQLDatasource.java

1. $subject Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2355
2. Skip master build for doc changes (https://github.com/ballerina-platform/ballerina-standard-library/issues/2362)

Validate connection pool configurations

---

.gitignore
ballerina/build.gradle
build.gradle
compiler-plugin-tests/build.gradle
compiler-plugin-tests/src/test/java/io/ballerina/stdlib/sql/compiler/CompilerPluginTest.java
compiler-plugin-tests/src/test/resources/diagnostics/sample2/Ballerina.toml
compiler-plugin-tests/src/test/resources/diagnostics/sample2/main.bal
compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/Constants.java
compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/SQLCodeAnalyzer.java
compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/SQLDiagnosticsCodes.java
compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/Utils.java
compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/analyzer/MethodAnalyzer.java
compiler-plugin/src/main/java/module-info.java

$subject
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/2058
TODOs in the code are related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2388 and will be closed with the same issue.

Add code analyser for type description param of OutParameter object

---

compiler-plugin-tests/src/test/java/io/ballerina/stdlib/sql/compiler/CompilerPluginTest.java
compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/analyzer/MethodAnalyzer.java
gradle.properties

$subject
This also includes the ballerina Gradle plugin update part of https://github.com/ballerina-platform/ballerina-standard-library/issues/2396

Improve efficiency of sql compiler plugin

---

compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/analyzer/MethodAnalyzer.java

Fix failure for method call for lang lib functions

---

compiler-plugin-tests/src/test/java/io/ballerina/stdlib/sql/compiler/CompilerPluginTest.java
compiler-plugin-tests/src/test/resources/diagnostics/sample3/Ballerina.toml
compiler-plugin-tests/src/test/resources/diagnostics/sample3/main.bal
compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/Constants.java
compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/SQLDiagnosticsCodes.java
compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/Utils.java
compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/analyzer/MethodAnalyzer.java

$subject 
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/2058
N/A

Improve inferring error for OutParameter

---

ballerina/tests/call-procedures-test.bal
ballerina/tests/connection-init-test.bal
ballerina/tests/connection-pool-test.bal
ballerina/tests/execute-basic-test.bal
ballerina/tests/local-transaction-test.bal

Remove usages of var

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
changelog.md
gradle.properties

$subject
Part of  https://github.com/ballerina-platform/ballerina-standard-library/issues/2503
N/A

Update module and distribution version

---

ballerina/Module.md
ballerina/client.bal
ballerina/connection-pool.bal
ballerina/error.bal
ballerina/types.bal

$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/2580

Improve API docs

---

ballerina/Module.md
docs/spec/spec.md

Improve description in the spec

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
changelog.md
compiler-plugin-tests/src/test/java/io/ballerina/stdlib/sql/compiler/CompilerPluginTest.java
compiler-plugin-tests/src/test/resources/diagnostics/sample4/Ballerina.toml
compiler-plugin-tests/src/test/resources/diagnostics/sample4/main.bal
compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/analyzer/ConnectionPoolConfigAnalyzer.java
gradle.properties

Fixes:
Added fixes:
https://github.com/ballerina-platform/module-ballerina-sql/pull/474

Patch release for SQL 1.2.1

---

docs/spec/spec.md

Improve spec introduction

---

.github/pull_request_template.md
.github/workflows/central-publish.yml
.github/workflows/publish-release.yml
.github/workflows/trivy-scan.yml

$subject 
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2483

Add create lib directory step

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
changelog.md
gradle.properties

Reverts ballerina-platform/module-ballerina-sql#508

Revert "[Automated] Sync master after 1.3.1 release"

---

README.md
ballerina/Module.md
ballerina/Package.md
docs/spec/spec.md

$subject
Fixes:
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2748

Change doc titles to sentence can and remove -ing

---

changelog.md
compiler-plugin-tests/src/test/java/io/ballerina/stdlib/sql/compiler/CompilerPluginTest.java
compiler-plugin-tests/src/test/resources/diagnostics/sample2/main.bal
compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/Constants.java
compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/Utils.java
compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/analyzer/MethodAnalyzer.java

Related issues: https://github.com/ballerina-platform/ballerina-standard-library/issues/2893

Add validation for time constructs in compiler plugin

---

gradle.properties

Update to lang version `2201.1.0-rc1.12`

---

gradle.properties

Update lang to latest rc version

---

gradle.properties

Update to stable version of ballerina lang

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
ballerina/tests/call-procedures-test.bal
ballerina/tests/query-row-test.bal
gradle.properties
native/src/main/java/io/ballerina/stdlib/sql/Constants.java
native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/AbstractResultParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/DefaultResultParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/utils/Utils.java

Fix build failure with ballerina-lang version 2201.2.0

Fix test failures due to reference types

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
ballerina/tests/complex-query-test.bal
ballerina/tests/query-row-test.bal
changelog.md
native/src/main/java/io/ballerina/stdlib/sql/Constants.java
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/QueryProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/utils/RecordIteratorUtils.java
native/src/main/java/io/ballerina/stdlib/sql/utils/Utils.java

$subject
Related issue: https://github.com/ballerina-platform/module-ballerina-sql/pull/533

Fix NullPointerException when retrieving record with default value for update 1

---

changelog.md

Update dependency order
Update changelog
Fixes:

Sync 2201.1.x to master

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
ballerina/tests/call-procedures-test.bal
ballerina/tests/complex-query-test.bal
ballerina/tests/query-row-test.bal
native/src/main/java/io/ballerina/stdlib/sql/Constants.java
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/CallProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/OutParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/QueryProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/DefaultResultParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/utils/ProcedureCallResultUtils.java
native/src/main/java/io/ballerina/stdlib/sql/utils/Utils.java

$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3041

Improve handling of reference types

---

ballerina/Dependencies.toml
ballerina/tests/complex-query-test.bal
ballerina/tests/query-row-test.bal
gradle.properties
native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/DefaultResultParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/DefaultStatementParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/utils/Utils.java

$subject part of https://github.com/ballerina-platform/ballerina-standard-library/issues/3128

Update dependency versions

---

ballerina/Ballerina.toml
build-config/resources/Ballerina.toml
build.gradle
gradle.properties

$subject 
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/3117

Add details for dependant jars

---

.github/workflows/update-spec.yml

$subject
Related to [#3154](https://github.com/ballerina-platform/ballerina-standard-library/issues/3154)
N/A

Add stdlib specs update workflow

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
gradle.properties
native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/sql-native/proxy-config.json
native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/sql-native/reflect-config.json
native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/sql-native/resource-config.json

Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3446
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/3315

Add configurations for native-image build

---

native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/sql-native/reflect-config.json
native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/sql-native/resource-config.json

$subject 
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3446
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/3315

Remove native-image reflections and resources used only in test cases

---

native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/sql-native/reflect-config.json

$Subject
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/3448

Update configurations in reflect config file

---

README.md
ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
ballerina/Package.md
build-config/resources/Ballerina.toml
changelog.md
docs/spec/spec.md
gradle.properties

Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3463

Update to Update 3 dependencies

---

.trivyignore
ballerina/Ballerina.toml
ballerina/tests/query-row-test.bal
ballerina/tests/simple-params-query-test.bal
gradle.properties

$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3575
N/A

Update to latest HSSQL driver dependency

---

test-utils/src/main/resources/META-INF/native-image/io.ballerina.stdlib/sql-test-utils/reflect-config.json
test-utils/src/main/resources/META-INF/native-image/io.ballerina.stdlib/sql-test-utils/resource-config.json

This should fix test failures in native test workflows
N/A

Add additional native-image configs needed to run tests

---

test-utils/src/main/resources/META-INF/native-image/io.ballerina.stdlib/sql-test-utils/reflect-config.json

Add missing reflection configs for tests

---

.github/workflows/update-spec.yml

Fix spec workflow not running for changes within  spec folder

---

.github/workflows/pull-request.yml
ballerina/Dependencies.toml
gradle.properties
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/QueryProcessor.java

$subject
https://github.com/ballerina-platform/ballerina-standard-library/issues/3517

Fix failing build for type reference support

---

.github/workflows/pull-request.yml
.github/workflows/update-spec.yml
ballerina/connection-pool.bal
ballerina/tests/connection-init-test.bal
changelog.md
compiler-plugin-tests/src/test/java/io/ballerina/stdlib/sql/compiler/CompilerPluginTest.java
compiler-plugin-tests/src/test/resources/diagnostics/sample1/main.bal
compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/SQLDiagnosticsCodes.java
compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/analyzer/ConnectionPoolConfigAnalyzer.java
gradle.properties
native/src/main/java/io/ballerina/stdlib/sql/datasource/SQLDatasource.java
native/src/main/java/io/ballerina/stdlib/sql/utils/Utils.java
test-utils/src/main/resources/META-INF/native-image/io.ballerina.stdlib/sql-test-utils/reflect-config.json
test-utils/src/main/resources/META-INF/native-image/io.ballerina.stdlib/sql-test-utils/resource-config.json

Sync update4 branch with master

---

.github/workflows/build-with-bal-test-native.yml

Disable native tests in windows env

---

ballerina/Dependencies.toml
changelog.md
native/src/main/java/io/ballerina/stdlib/sql/Constants.java
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/ClientProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/utils/Utils.java

$subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/3763

Enable non-Hikari logs

---

native/src/main/java/io/ballerina/stdlib/sql/utils/Utils.java

Fix `null` return for type-reference record constraint

---

.github/workflows/build-with-bal-test-native.yml
README.md

Update GraalVM Check action workflow name

---

compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/Constants.java
compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/Utils.java
compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/analyzer/ConnectionPoolConfigAnalyzer.java
compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/analyzer/MethodAnalyzer.java

Improve compiler error check before analysing

---

ballerina/Dependencies.toml
gradle.properties

[2201.3.x] Update Mime and HTTP versions

---

README.md
ballerina/Module.md
ballerina/Package.md
ballerina/types.bal

Fix formatting on API docs

---

README.md
ballerina/Module.md
ballerina/Package.md
ballerina/client.bal
ballerina/types.bal
changelog.md

$Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3857

Improve API docs based on Best practices

---

.github/workflows/build-with-bal-test-native.yml
ballerina/build.gradle

Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/3755
Temporary fix until this [improvement](https://github.com/ballerina-platform/ballerina-lang/issues/38826) is done from lang-side
N/A

Add a temporary task to remove transaction tests for native build

---

ballerina/Dependencies.toml
ballerina/tests/schema_client.bal
gradle.properties

Update to latest dependencies

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/ExecuteProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/utils/ErrorGenerator.java

Fix the batch execute API OOM exception

---

.github/workflows/pull-request.yml

$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4098

Add codecov token to the pr check

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
changelog.md
docs/spec/spec.md
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/ExecuteProcessor.java

$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4129

Optimise batchExecute with a batch size of 1000

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
changelog.md
docs/spec/spec.md
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/ExecuteProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/utils/ErrorGenerator.java

$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4129

Optimise batchExecute with a batch size of 1000 

---

gradle.properties

Update http and oauth2 versions

---

.github/workflows/build-timestamped-master.yml
.github/workflows/pull-request.yml
ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
compiler-plugin-tests/build.gradle
compiler-plugin-tests/src/test/java/io/ballerina/stdlib/sql/compiler/CompilerPluginTest.java
compiler-plugin-tests/src/test/resources/diagnostics/sample1/main.bal
compiler-plugin-tests/src/test/resources/diagnostics/sample2/main.bal
compiler-plugin-tests/src/test/resources/diagnostics/sample4/main.bal
compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/Constants.java
compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/Utils.java
gradle.properties

$subject
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/3119
N/A

Enable coverage for compiler plugin

---

changelog.md
native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/AbstractStatementParameterProcessor.java

$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4200
N/A

Handle null error messages from underlying drivers

---

native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/DefaultResultParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/utils/Utils.java

$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2568

Update use of depreciated `ValueCreator.createMapValue()` API

---

.github/workflows/pull-request.yml

$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4221

Introduce concurrency setting

---

ballerina/Dependencies.toml
gradle.properties

Update lang and dependency versions

---

native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/CallProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/OutParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/AbstractStatementParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/DefaultStatementParameterProcessor.java

This is to support the build for https://github.com/ballerina-platform/ballerina-standard-library/issues/4344

Fix object getType() API usage

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
gradle.properties

Update the dependency versions for Swan Lake Update 6 

---

ballerina/Dependencies.toml
gradle.properties

Update dependency versions for U7

---

ballerina/Dependencies.toml
native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/DefaultStatementParameterProcessor.java

$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4531

Return the error when database doe not support the given time type

---

ballerina/tests/complex-query-test.bal
ballerina/tests/query-row-test.bal
ballerina/tests/resources/sql/query/complex-test-data.sql
ballerina/tests/resources/sql/query/query-row-test-data.sql
changelog.md
native/src/main/java/io/ballerina/stdlib/sql/utils/Utils.java

$subject 
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4588

Support retrieval of enums

---

gradle.properties

Update http and transaction dependencies

---

.github/workflows/build-timestamped-master.yml
.github/workflows/central-publish.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
.github/workflows/trivy-scan.yml
.github/workflows/update-spec.yml
README.md
ballerina/Ballerina.toml
build-config/checkstyle/build.gradle
build-config/resources/Ballerina.toml
build-config/spotbugs-exclude.xml
compiler-plugin-tests/build.gradle
compiler-plugin/src/main/java/io/ballerina/stdlib/sql/compiler/Constants.java
gradle.properties
gradle/wrapper/gradle-wrapper.properties
native/build.gradle
test-utils/src/main/java/io/ballerina/stdlib/sql/testutils/CallTestUtils.java
test-utils/src/main/java/io/ballerina/stdlib/sql/testutils/ClientTestUtils.java

Migrate to Java 17

---

.github/workflows/build-timestamped-master.yml
.github/workflows/central-publish.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
.github/workflows/trivy-scan.yml
gradle.properties

Update java-version to 17.0.7

---

.github/workflows/pull-request.yml

Inherit secrets for codecov

---

compiler-plugin-tests/src/test/java/io/ballerina/stdlib/sql/compiler/CompilerPluginTest.java
compiler-plugin-tests/src/test/resources/testng.xml

Related to https://github.com/ballerina-platform/ballerina-library/issues/5872
As mentioned here, https://github.com/ballerina-platform/ballerina-lang/issues/41866 first attempt to resolve always seems to fail

Disable compiler plugin tests temporarily

---

ballerina/types.bal

Fix API Docs

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties

Update lang and dependencies for update 09

---

.github/workflows/build-timestamped-master.yml
.github/workflows/build-with-bal-test-graalvm.yml
.github/workflows/central-publish.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
.github/workflows/trivy-scan.yml

Update the workflow template links

---

native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/AbstractStatementParameterProcessor.java

Add a comment tagging the issue for future reference

---

changelog.md
native/src/main/java/io/ballerina/stdlib/sql/datasource/SQLDatasource.java
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/CallProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/ExecuteProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/QueryProcessor.java

Fixes: https://github.com/ballerina-platform/ballerina-library/issues/6641

Run database queries inside transaction block as non blocking query 

---

.github/workflows/build-with-bal-test-graalvm.yml
.github/workflows/central-publish.yml
.github/workflows/pull-request.yml
.github/workflows/trivy-scan.yml

Update workflow files

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties

Update the version for the update 10 release

---

ballerina/Dependencies.toml
gradle.properties

Update JWT and HTTP versions

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
gradle.properties

Related to: https://github.com/ballerina-platform/module-ballerina-sql/pull/735

Update patch version

---

ballerina/tests/call-procedures-test.bal
changelog.md
docs/spec/spec.md
native/src/main/java/io/ballerina/stdlib/sql/Constants.java
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/CallProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/OutParameterProcessor.java

Fixes: https://github.com/ballerina-platform/ballerina-library/issues/7255

Fix stored procedure call having output parameter failing with error

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
ballerina/tests/call-procedures-test.bal
changelog.md
docs/spec/spec.md
native/src/main/java/io/ballerina/stdlib/sql/Constants.java
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/CallProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/OutParameterProcessor.java

Fixes: https://github.com/ballerina-platform/ballerina-library/issues/7255

[2201.9.x] Fix stored procedure call having output parameter failing with error

---

native/src/main/java/io/ballerina/stdlib/sql/datasource/SQLWorkerThreadPool.java

Fixes: https://github.com/ballerina-platform/ballerina-library/issues/7308
Related PR: https://github.com/ballerina-platform/module-ballerina-sql/pull/735

Improve query performance

---

gradle.properties

Update Http and OAuth2 timestamp

---

build-config/resources/Ballerina.toml
build.gradle
gradle.properties
native/src/main/java/io/ballerina/stdlib/sql/datasource/PoolKey.java
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/CallProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/OutParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/nativeimpl/QueryProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/AbstractStatementParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/DefaultResultParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/parameterprocessor/DefaultStatementParameterProcessor.java
native/src/main/java/io/ballerina/stdlib/sql/utils/ProcedureCallResultUtils.java
native/src/main/java/io/ballerina/stdlib/sql/utils/Utils.java
native/src/test/java/io/ballerina/stdlib/sql/TestUtils.java
native/src/test/java/io/ballerina/stdlib/sql/nativeimpl/OutParameterProcessorTest.java
native/src/test/java/io/ballerina/stdlib/sql/parameterprocessor/DefaultResultParameterProcessorTest.java
native/src/test/java/io/ballerina/stdlib/sql/parameterprocessor/DefaultStatementParameterProcessorTest.java

[Java21] Migrate to new runtime APIs

---

.github/workflows/build-timestamped-master.yml
.github/workflows/build-with-bal-test-graalvm.yml
.github/workflows/central-publish.yml
.github/workflows/publish-release.yml
.github/workflows/pull-request.yml
.github/workflows/trivy-scan.yml

Update workflows to use 2201.10.x template

---

.gitignore

Ignore .cache directory

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
gradle.properties

Update library timestamp versions

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
gradle.properties
native/src/main/java/io/ballerina/stdlib/sql/datasource/SQLDatasource.java

Remove string conversion in connection properties

---

gradle.properties

Change ballerina lang version
